$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train_model
display_name: train_model
version: 1

inputs: 
  data:
    type: uri_file
  random_state:
    type: integer
    default: 42
  criterion:
    type: string
    default: gini
  max_depth:
    type: integer
    default: 10
  min_samples_split:
    type: integer
    default: 2
  min_samples_leaf: 
    type: integer
    default: 1
  max_features:
    type: string
    default: sqrt

outputs:
  model_output:
    type: mlflow_model
  test_data:
    type: 
  

