trigger: none

variables:
- group: mymodel-vars

stages:
- stage: build
  jobs:
  - job:
    pool:
      vmImage: 'Ubuntu-latest'
    steps: 
    - script: |
        echo 'I would build some artifacts here'
      displayName: 'Download Artifacts'
- stage: qa
  dependsOn: 
    - build
  jobs:
  - deployment: QualityAssurance
    displayName: Deploy to QA
    pool:
      vmImage: 'Ubuntu-latest'
    environment: 'myenv-qa'
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: |
              echo 'I would deploy a model to an ACI here'
            displayName: 'Deploy to QA ACI'
- stage: preprod
  dependsOn: 
    - qa
  jobs:
  - deployment: DeployToPreProduction
    displayName: Deploy to PreProduction
    pool:
      vmImage: 'Ubuntu-latest'
    environment: 'myenv-preprod'
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: |
              echo 'This would be deployed to an AKS cluster and ready to be switched over'
            displayName: 'Deploy to Pre Prod AKS'
- stage: prod
  dependsOn: 
    - preprod
  jobs:
  - deployment: DeployToProduction
    displayName: Deploy to Production
    pool:
      vmImage: 'Ubuntu-latest'
    environment: 'myenv-prod'
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: |
              echo 'Finally deploy to production'
            displayName: 'Deploy to AKS'
