FROM YOURACRNAME.azurecr.io/USERNAME/IMAGENAME:latest
# Above, define your starting container
# Define the entry point for your container
ENTRYPOINT [ "uvicorn","src.main.python.app:app","--host", "0.0.0.0","--port","8080"]